:arrow_up: Upgrade node version and gatsby-transformer-sharp to fix image processing
Although builds are working fine locally, since upgrading gatsby and gatsby-plugin-sharp, the deploys on CircleCI are failing with the following message:

error Failed to process image /home/circleci/chareads.com/src/assets/cover.jpg
Error: Input file contains unsupported image format